server:
  port: 5000

#logging:
#  level:
#    com:
#      netflix:
#        eureka: OFF
#        discovery: OFF

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: SERVICE
  datasource:
    url: jdbc:h2:mem:fintechdb
    usename: root
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect

#  datasource:
#    password: password
#    url: jdbc:mysql://fintechdb.ccdo9omzcuea.us-east-1.rds.amazonaws.com:3306/accountdb
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#      show_sql: true
