server:
  port: 9002

eureka:
  instance:
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 28
    prefer-ip-address: true
#    ip-address: http://server-env.eba-ghkahchb.us-east-1.elasticbeanstalk.com
  client:
    service-url:
      defaultZone: http://server-env.eba-ghkahchb.us-east-1.elasticbeanstalk.com/eureka/

spring:
  application:
    name: ACCOUNT
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:fintechdb
    usename: root
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    password: password
#    url: jdbc:mysql://fintechdb.ccdo9omzcuea.us-east-1.rds.amazonaws.com:3306/accountdb
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#      show_sql: true