server:
  port: 9008

spring:
  application:
    name: RABBITMQ
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/accountdb
    username: root
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
        show_sql: true



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost