server:
  port: 9004

spring:
  application:
    name: GATEWAY
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  cloud:
    gateway:
      routes:
        - id: ACCOUNT
          uri: lb://ACCOUNT
          predicates:
            - Path=/account/**
        - id: TRANSACTION
          uri: lb://TRANSACTION
          predicates:
            - Path=/transaction/**
        - id: NOTIFICATION
          uri: lb://NOTIFICATION
          predicates:
            - Path=/notification/**
        - id: EMAIL
          uri: lb://EMAIL
          predicates:
            - Path=/mailer/**
  datasource:
    url: jdbc:h2:mem:fintechdb
    usename: root
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect

#  datasource:
#    password: password
#    url: jdbc:mysql://fintechdb.ccdo9omzcuea.us-east-1.rds.amazonaws.com:3306/notificationdb
#    username: root
#    jpa:
#      hibernate:
#        ddl-auto: create
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL8Dialect
#          format_sql: true
#        show_sql: true

eureka:
  instance:
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 28
    prefer-ip-address: true
    ip-address: ${EUREKA_IP:localhost}
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:5000/eureka/}
