server:
  port: 9999

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

spring:
  application:
    name: EMAIL
  mail:
    host: smtp.gmail.com
    port: 587
    username: salcsjoe@gmail.com
    password: Jonathan12_.xx
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
