server:
  port: 9999

eureka:
  instance:
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 28
    prefer-ip-address: true
#    ip-address: ${EUREKA_IP:localhost}
  client:
    service-url:
      defaultZone: http://server-env.eba-ghkahchb.us-east-1.elasticbeanstalk.com/eureka/

spring:
  application:
    name: EMAIL
  mail:
    host: smtp.gmail.com
    port: 587
    username: salcsjoe@gmail.com
    password: Jonathan12_.xx
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com