server:
  port: 9000

eureka:
  instance:
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 28
    prefer-ip-address: true
    ip-address: ${EUREKA_IP:localhost}
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:5000/eureka/}

jwt:
  secret: reloadlyisgr

spring:
  application:
    name: TRANSACTION
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  datasource:
    url: jdbc:h2:mem:fintechdb
    usename: root
    password: password
    driver-class-name: org.h2.Driver
    jpa:
      spring:
        jpa:
          database-platform: org.hibernate.dialect.H2Dialect

#  datasource:
#    password: password
#    url: jdbc:mysql://fintechdb.ccdo9omzcuea.us-east-1.rds.amazonaws.com:3306/transactiondb
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#      show_sql: true